version: "3.8"
services:
  blockchain:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command:
      - "--accounts=10"
      - "--defaultBalanceEther=1000"
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - blockchain
